### ISSUE TITLE
Glossary & relative links

### ISSUE THREAD

**Issue by u8sand** [nih-cfde/the-fair-cookbook#15]
One thing we've been doing for some terms is linking to the glossary:

`https://github.com/nih-cfde/specifications-and-documentation/blob/master/draft-CFDE_glossary/glossary.md#SomeGlossaryTerm`

But this glossary is not actually public.. do we have a glossary in the cookbook that we can link to?

If there is a glossary, or even if we want to link to other chapters, how does one create a relative hyperlink? `./relative_path`, `/absolute_path`, something else?

**Comment by proccaserra** [comment]
@u8sand we touched on the issue and was hoping to avoid having to duplicate the information we currently have.
We could have a `glossary.md` placeholder (file + entry in toc), until we either obtain clearance to use the existing resource or have a decision about create a dedicated glossary for the cookbook.

@RLC-DCPPC @ACharbonneau what are your thoughts?

This echoes also the discussion we're having with @abradyIGS regarding the C2M2 model documentation.

**Comment by ACharbonneau** [comment]
The idea with the glossary is that https://github.com/nih-cfde/specifications-and-documentation/blob/master/draft-CFDE_glossary/glossary.md is the main and ever growing glossary. It holds everything, and far more terms than would be useful for any one use. As things are published or turned in to NIH, we extract the glossary terms relevant to that object and make a glossary specific to that. as in: https://github.com/nih-cfde/specifications-and-documentation/tree/master/draft-C2M2_specification_with_Levels

**Comment by ACharbonneau** [comment]
I am 90% sure the glossary issue has been solved, and in a different way than I described earlier. If you find any broken glossary links at https://cfde-published-documentation.readthedocs-hosted.com/en/latest/ please make a new issue for them either here or in the website repo https://github.com/nih-cfde/published-documentation
