### ISSUE TITLE
The What is FAIR? page is not complete

### ISSUE THREAD

**Issue by AviMaayan** [nih-cfde/the-fair-cookbook#28]
It has some cross out and To Do sections.

**Comment by dcfcjcheadle** [comment]
Hi Avi,
Thanks for bringing my attention to this, admittedly it slipped off my radar.  That section (How to contribute, reform, evolve evaluation rules?) does indeed need input and was included to be a direct answer to one of Amanda's questions in nih-cfde/training-and-engagement#38.

I'm happy to flesh out this section but need a bit more to go on.  Could you (or @proccaserra) provide some sort of contact point to route DCCs to for the purpose of discussing their FAIRshake evaluations?  If I'm understanding Philippe's comments correctly, there are some GitHub repositories that contain information, and a FAIR working group;  If contact for that FAIR working group is linked on a CFDE-facing website, that would probably be perfect.  Please let me know and I'll create a new PR for this!

**Comment by AviMaayan** [comment]
Hi @dcfcjcheadle, I am not aware of establishing a contact or a working group that DCCs can go to to "discuss their FAIRshake evaluations". I think it is a good idea, but for the June 17 demo, I think we should just state that such working group will become established once the DCCs are on board. This working group will and should include DCC members so they can collectively define what it means to be FAIR and which FAIR compliance aspects and actions are most important.

**Comment by dcfcjcheadle** [comment]
Building on the edits from @proccaserra I created a pull request to clean up my TODO's (cleaning up some wording and removing a link to a recipe that isn't currently in the cookbook) and fixing some formatting that went weird.

**Comment by dcfcjcheadle** [comment]
Hi @AviMaayan the fixes have been merged into the dev branch.  OK to close?

**Comment by AviMaayan** [comment]
Yes.
