### ISSUE TITLE
Edits for the Evaluating FAIRness recipe

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/the-fair-cookbook#44]
Hi @AviMaayan and @u8sand,

@abhijna  and I reviewed the [Evaluating FAIRness with FAIRshake recipe](https://cfde-published-documentation.readthedocs-hosted.com/en/latest/the-fair-cookbook/content/recipes/04/fairshake/). 

Ahead of the CFDE portal release deadline, we'd like to request the edits below to help answer questions new users might have and that we had in [this issue](https://github.com/nih-cfde/training-and-engagement/issues/38). Please comment in the issue with any questions! Feel free to break these into smaller Github issues, we put everything here for context. :)

## Suggested additions to current documentation

We'd like for this recipe to help users 1) do an assessment and 2) interpret the output of the assessment so they can determine how to move forward with improving their FAIR score. We read through this recipe, but were unable to find obvious answers to the following questions:
- How does FAIRshake evaluate interoperability?
- How can I increase a specific FAIR score?
- How do I read/understand the FAIR insignia?
- How do I dispute/correct/change/question my FAIR rating?

We suggest adding a new use case scenario section/framework to the recipe to answer these questions with an example researcher. For example, Janice, a researcher at a Common Fund program, has just completed an assessment using the automated CFDE rubric metrics on FAIRshake for a metadata object. We'd like this section to explain: 
1) how she should interpret the resulting FAIRshake insignia (e.g., provide an example insignia and walk us through interpretation of the different boxes, colors, percents (displayed when mouse hovers over box))
2) where she should look on the FAIRshake website/insignia to determine the interoperability of her assessed metadata
3) what outputs she should look at to understand how FAIRshake arrived at the numerical scores of the assessment (e.g., is there a graphical/tabular output to look at?)
4) how she can improve the overall and component FAIR scores (e.g., understand why persistent identifier was scored as 11% and how to make it higher)
5) how she can dispute/correct/change/question the FAIR score (e.g., how to ask for help?)

Some of the information in the FAIRshake Documentation page/youtube videos would be very useful to add to this recipe (e.g., anatomy of insignia figure). We also recommend making the Documentation page a link on the top navigation bar of the FAIRshake website so it is more prominent; it's easy to miss at the bottom of the page! 

### Check hyperlinks
- When the website is opened in an incognito web browser page, some of the website links on the fair cookbook recipe are broken:
    - "transformed to DATS" link to a Github repo
    - "You can refer to the scripts here for examples on how you can accomplish this" link
- There are some links to the glossary page. It would be helpful to link to the entries instead of the top of the page:
    - e.g., for "FAIR", "FAIRshake", "RDF", "JSON Schema", "JSON", "DATS"

### Ingredients section
There seem to be two processes documented in this recipe - conducting an assessment and publishing assessment metrics. A use case example for each of the ingredients and processes would help clarify the objectives of the recipe.
- For example, for "Machine-readable (ideally standardized) metadata description for enabling automated assessments" - Can you provide an example and where the metadata might come from?

### FAIR metrics by fairmetrics.org

"To perform an assessment with this rubric, we'll need something to assess. For this, you can find a digital object already in FAIRshake or register your own (with 'create object' at the bottom of the rubric)."
- The figure above this sentence shows the rubric page. It does not have a search bar. The figure below this sentence has a search bar. Could you clarify how the user can navigate from the first screenshot page to the next?
- Could you add a screenshot of the "Create New Digital Object" button? How does one navigate to that page?
- It would be very helpful to users if you could add a few tutorial steps with answers to the questions in the manual rubric, including steps users could try with a specific digital object. 
- It would also help if you could include screenshots from the digital object's interface/website where these answers can be found. For example, if you are evaluating the GTEx portal, where would you look for a "persistent identifier".

### Automated rubric for DATS
Here are some questions that we had while trying to understand the automated rubric:
    1) What's the first step? What's the input file?
    2) Where should I run this code? Or what should I do with the script?
    3) Where do I see the FAIR score?
    
It would be very helpful to add step-by-step tutorials with screenshots of input files, outputs, fair scores and their interpretation in this documentation. The details from the [Preparing to perform automated assessments](https://cfde-published-documentation.readthedocs-hosted.com/en/latest/the-fair-cookbook/content/recipes/04/fairshake/#preparing-to-perform-automated-assessments) section onwards is quite detailed with technical information, however a new user is unlikely to have enough context to understand how to apply this information. Adding more specific examples about when and how this part of the recipe should be used would be very helpful.

**Comment by AviMaayan** [comment]
Hi @marisalim and @abhijna, Thank you for your great feedback. We are working on addressing these comments and suggestions... 

cc: @u8sand @sherry-jenkins

**Comment by marisalim** [comment]
Hi @u8sand, @abhijna and I are reviewing the changes. So far they look great and the addition of the use case scenario is exactly what we were looking for - we have some minor revisions and a few questions. We'll post them later today or tomorrow!

**Comment by marisalim** [comment]
Hi @u8sand, we added comments to the recipe on this [hackmd doc](https://hackmd.io/yt0Z6EZ6Ske-hzbrrHLROQ?view) (click on "Comments" at the top of the page to view comments side-by-side with the recipe text). Let us know if you have questions!

**Comment by abhijna** [comment]
The edits and new content are very helpful and clarify things. Thanks for incorporating all these changes so quicky :)

**Comment by u8sand** [comment]
Thank you for your in depth review and helpful feedback for this recipe; I believe it likely has become much more useful and expect we'll re-use it for better documenting FAIRshake as well.
