### ISSUE TITLE
Missing images (broken links to images) in the Schema.org, BioSchemas, JSONSchema, JSON-LD and DATS recipe

### ISSUE THREAD

**Issue by AviMaayan** [nih-cfde/the-fair-cookbook#58]
https://docs.nih-cfde.org/en/latest/the-fair-cookbook/content/recipes/Discoverability/seo/

**Comment by u8sand** [comment]
This seems related to several disconnects:
- As #46 has not been addressed to support relative images in recipes, this is destined to fail again in the future.
- the `master` branch folder layout was changed and the images reference absolute paths in that branch.
  - the relevant image is still here in the dev branch <https://raw.githubusercontent.com/nih-cfde/the-fair-cookbook/dev/content/recipes/07/images/ss1.png>

I will update the images to the current locations in production, also for #50
